### ISSUE TITLE
question abot the split of vqa_rad dataset

### ISSUE THREAD

**Issue by Adam-lxd** [zhjohnchan/ARL#3]
Hi, thanks for your excellent work. It helps me a lot when processing datasets. 
I downloaded vqa_rad dataset and found no `json` in the zip file. But in your [code](https://github.com/zhjohnchan/ARL/blob/527fe06a8811f8267a78ff82d45fd5c7136751b3/prepro/prepro_finetuning_data.py#L116), it needs `json` files to process. Then I found a processed vqa_rad dataset in [link](https://github.com/aioz-ai/MICCAI19-MedVQA). It does have `json` files except `valset.json`. I guess you split the dataset in your way. Could you share the code of how you are splitting them? 
Thanks! :)

**Comment by zhjohnchan** [comment]
Hi,

Thanks for your attention! :-)

We adopted its typical split in our experiments. We duplicated  `testset.json` as `valset.json` to unify the code interface for simplicity. Sorry for confusing you!

Best,
Zhihong

**Comment by Adam-lxd** [comment]
Thank you so much for your speedy reply again!!!  :)
