### ISSUE TITLE
seems a problem of prepro_finetuning_data.py

### ISSUE THREAD

**Issue by Adam-lxd** [zhjohnchan/ARL#5]
Hi @zhjohnchan, 
   Thanks for your excellent work. I tried to enhance my model by adding "knowledge", but encountered an issue when processing the finetuning data. I followed the code [prepro_finetuning_data](https://github.com/zhjohnchan/ARL/blob/527fe06a8811f8267a78ff82d45fd5c7136751b3/prepro/prepro_finetuning_data.py#L86) to extract entities using scispacy_linker. However, the result returned an empty entity set, indicating that there were no entities present.   Consequently, the code [base_dataset](https://github.com/zhjohnchan/ARL/blob/527fe06a8811f8267a78ff82d45fd5c7136751b3/arl/datasets/base_dataset.py#LL226C4-L226C4) included entities, which cannot be stacked together due to their different shapes (0, 1, 2).
I suspect that the discrepancy may be due to a different version of "en_core_sci_scibert". Have you ever faced a similar problem before?
Best regards.

**Comment by Adam-lxd** [comment]
In my work to resolve the issue, the **entity_embeddings** was removed from **flatten_encodings** in base_dataset.py at [line 226](https://github.com/zhjohnchan/ARL/blob/527fe06a8811f8267a78ff82d45fd5c7136751b3/arl/datasets/base_dataset.py#L226). The **mlm_collator** is used for stacking of **mlm_embeddings**, which was not necessary for my work.

**Comment by rhyhck** [comment]
> Hi @zhjohnchan, Thanks for your excellent work. I tried to enhance my model by adding "knowledge", but encountered an issue when processing the finetuning data. I followed the code [prepro_finetuning_data](https://github.com/zhjohnchan/ARL/blob/527fe06a8811f8267a78ff82d45fd5c7136751b3/prepro/prepro_finetuning_data.py#L86) to extract entities using scispacy_linker. However, the result returned an empty entity set, indicating that there were no entities present. Consequently, the code [base_dataset](https://github.com/zhjohnchan/ARL/blob/527fe06a8811f8267a78ff82d45fd5c7136751b3/arl/datasets/base_dataset.py#LL226C4-L226C4) included entities, which cannot be stacked together due to their different shapes (0, 1, 2). I suspect that the discrepancy may be due to a different version of "en_core_sci_scibert". Have you ever faced a similar problem before? Best regards.

Hello, Have you runned the "pretrain_arl.sh"? I meet some question, can you help me ?

**Comment by rhyhck** [comment]
> In my work to resolve the issue, the **entity_embeddings** was removed from **flatten_encodings** in base_dataset.py at [line 226](https://github.com/zhjohnchan/ARL/blob/527fe06a8811f8267a78ff82d45fd5c7136751b3/arl/datasets/base_dataset.py#L226). The **mlm_collator** is used for stacking of **mlm_embeddings**, which was not necessary for my work.

Hello, have you uesd the "en_core_sci_scibert-0.5.4" library? I can't find its compressed file on the official website . Can you share it with me? Thank you!
